from app.models import db, Review
from datetime import datetime
from app.models.db import db, environment, SCHEMA


def seed_reviews():
    reviews = [
        Review(
            restaurant_id=1,
            user_id=1,
            order_id=1,
            review="The food was incredible and came out quickly! Definitely coming back.",
            order_rating=5,
            restaurant_rating=4,
        ),
        Review(
            restaurant_id=1,
            user_id=2,
            order_id=2,
            review="Food was delicious, but a bit too spicy for my taste. Still good overall.",
            order_rating=4,
            restaurant_rating=4,
        ),
        Review(
            restaurant_id=1,
            user_id=3,
            order_id=3,
            review="A decent experience. The service was fast, but the food could have been hotter.",
            order_rating=3,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=1,
            user_id=4,
            order_id=4,
            review="Absolutely fantastic! The flavor was on point, and the ambiance was great.",
            order_rating=5,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=1,
            user_id=5,
            order_id=5,
            review="Not the best experience. The food took longer than expected to arrive.",
            order_rating=2,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=2,
            user_id=1,
            order_id=6,
            review="Food was okay, but delivery was late and the order was cold.",
            order_rating=3,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=2,
            user_id=2,
            order_id=7,
            review="The food had good flavors, but the portion sizes were small for the price.",
            order_rating=4,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=2,
            user_id=3,
            order_id=8,
            review="It was an average meal. Nothing special, but it satisfied my hunger.",
            order_rating=3,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=2,
            user_id=4,
            order_id=9,
            review="The food tasted good, but the portion size was smaller than expected.",
            order_rating=3,
            restaurant_rating=4,
        ),
        Review(
            restaurant_id=2,
            user_id=5,
            order_id=10,
            review="I enjoyed the food, but I had to wait much longer than expected.",
            order_rating=4,
            restaurant_rating=4,
        ),
        Review(
            restaurant_id=3,
            user_id=1,
            order_id=11,
            review="Dessert was amazing! I couldn’t stop eating it.",
            order_rating=5,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=3,
            user_id=2,
            order_id=12,
            review="The dessert was good, but a bit too sweet for my liking.",
            order_rating=4,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=3,
            user_id=3,
            order_id=13,
            review="Desserts were delicious, but the service could have been a bit faster.",
            order_rating=4,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=3,
            user_id=4,
            order_id=14,
            review="The dessert was perfect. Sweet but not overwhelming. Will definitely return!",
            order_rating=5,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=3,
            user_id=5,
            order_id=15,
            review="Desserts were alright, but I expected more variety on the menu.",
            order_rating=3,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=4,
            user_id=1,
            order_id=16,
            review="The meal was delicious, but I had a long wait for my food.",
            order_rating=4,
            restaurant_rating=4,
        ),
        Review(
            restaurant_id=4,
            user_id=2,
            order_id=17,
            review="Great food, quick service, but the atmosphere could be better.",
            order_rating=4,
            restaurant_rating=4,
        ),
        Review(
            restaurant_id=4,
            user_id=3,
            order_id=18,
            review="Service was quick, but the food was bland and lacked seasoning.",
            order_rating=2,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=4,
            user_id=4,
            order_id=19,
            review="Delicious food, excellent ambiance, but I wish there was a vegetarian option.",
            order_rating=4,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=4,
            user_id=5,
            order_id=20,
            review="Food was good, but the prices were higher than I expected.",
            order_rating=3,
            restaurant_rating=4,
        ),
        Review(
            restaurant_id=5,
            user_id=1,
            order_id=21,
            review="The food arrived on time, but I was disappointed with the taste.",
            order_rating=2,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=5,
            user_id=2,
            order_id=22,
            review="It was an average meal. The food was okay, but it didn’t wow me.",
            order_rating=3,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=5,
            user_id=3,
            order_id=23,
            review="The food was decent, but the delivery time was longer than expected.",
            order_rating=3,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=5,
            user_id=4,
            order_id=24,
            review="It was a great experience. The food was tasty and the service was prompt.",
            order_rating=5,
            restaurant_rating=4,
        ),
        Review(
            restaurant_id=5,
            user_id=5,
            order_id=25,
            review="I was happy with the meal, but it was a little too greasy for my taste.",
            order_rating=3,
            restaurant_rating=3,
        ),
        Review(
            restaurant_id=6,
            user_id=1,
            order_id=26,
            review="Dessert was absolutely amazing. Best I’ve had in a long time!",
            order_rating=5,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=6,
            user_id=2,
            order_id=27,
            review="I loved the dessert, but the portion size was a bit too small.",
            order_rating=4,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=6,
            user_id=3,
            order_id=28,
            review="Amazing desserts, but I had to wait too long to get my order.",
            order_rating=4,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=6,
            user_id=4,
            order_id=29,
            review="The dessert was rich in flavor and texture, I would definitely recommend it!",
            order_rating=5,
            restaurant_rating=5,
        ),
        Review(
            restaurant_id=6,
            user_id=5,
            order_id=30,
            review="The dessert was good, but I was expecting more variety in the options.",
            order_rating=3,
            restaurant_rating=5,
        ),
    ]

    db.session.bulk_save_objects(reviews)
    db.session.commit()


def undo_reviews():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.reviews RESTART IDENTITY CASCADE;"
        )
    else:
        db.session.execute("DELETE FROM reviews;")
    db.session.commit()
